"""empty message

Revision ID: 29f6d05c3fe1
Revises: 
Create Date: 2018-05-04 14:43:55.098045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f6d05c3fe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Caterer',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('caterer_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('engagement_start', sa.DateTime(), nullable=False),
    sa.Column('engagement_end', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('Meal',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('meal_period', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('meal_period')
    )
    op.create_table('User',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('CatererLog',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('caterer_id', sa.String(), nullable=True),
    sa.Column('month', sa.String(length=15), nullable=False),
    sa.Column('isCompleted', sa.Boolean(), nullable=True),
    sa.Column('wasTerminated', sa.Boolean(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['Caterer._id'], ),
    sa.PrimaryKeyConstraint('_id', 'month')
    )
    op.create_table('FeedBack',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('meal_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('comment_by', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['Meal._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('Menu',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('meal_period', sa.String(length=15), nullable=False),
    sa.Column('caterer_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caterer_id'], ['Caterer._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('meal_period')
    )
    op.create_table('MenuDetail',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=True),
    sa.Column('menu_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category._id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['Menu._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('menu_name')
    )
    op.create_table('MealDetail',
    sa.Column('_id', sa.String(length=255), nullable=False),
    sa.Column('meal_id', sa.String(), nullable=True),
    sa.Column('menu_detail_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['Meal._id'], ),
    sa.ForeignKeyConstraint(['menu_detail_id'], ['MenuDetail._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MealDetail')
    op.drop_table('MenuDetail')
    op.drop_table('Menu')
    op.drop_table('FeedBack')
    op.drop_table('CatererLog')
    op.drop_table('User')
    op.drop_table('Meal')
    op.drop_table('Caterer')
    op.drop_table('Category')
    # ### end Alembic commands ###
